--@AUTHOR Jasmine Abtahi

-- CREATE THE TABLE
CREATE TABLE WAREHOUSE (
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	OnHandQuantity INT,
	OnHandQuantityDelta INT,
	event_type VARCHAR(10),
	event_datetime DATETIME
);

--DESCRIBE TABLE (SHOW METADATA) 
EXEC sp_help WAREHOUSE;

--INSERT VALUES INTO THE TABLE
INSERT INTO WAREHOUSE VALUES ('SH0013', 278,   99 ,   'OutBound', '2020-05-25 0:25');
INSERT INTO WAREHOUSE VALUES ('SH0012', 377,   31 ,   'InBound', '2020-05-24 22:00');
INSERT INTO WAREHOUSE VALUES ('SH0011', 346,   1  ,   'OutBound', '2020-05-24 15:01');
INSERT INTO WAREHOUSE VALUES ('SH0010', 346,   1  ,   'OutBound', '2020-05-23 5:00');
INSERT INTO WAREHOUSE VALUES ('SH009',  348,   102,   'InBound', '2020-04-25 18:00');
INSERT INTO WAREHOUSE VALUES ('SH008',  246,   43 ,   'InBound', '2020-04-25 2:00');
INSERT INTO WAREHOUSE VALUES ('SH007',  203,   2  ,   'OutBound', '2020-02-25 9:00');
INSERT INTO WAREHOUSE VALUES ('SH006',  205,   129,   'OutBound', '2020-02-18 7:00');
INSERT INTO WAREHOUSE VALUES ('SH005',  334,   1  ,   'OutBound', '2020-02-18 8:00');
INSERT INTO WAREHOUSE VALUES ('SH004',  335,   27 ,   'OutBound', '2020-01-29 5:00');
INSERT INTO WAREHOUSE VALUES ('SH003',  362,   120,   'InBound', '2019-12-31 2:00');
INSERT INTO WAREHOUSE VALUES ('SH002',  242,   8  ,   'OutBound', '2019-05-22 0:50');
INSERT INTO WAREHOUSE VALUES ('SH001',  250,   250,   'InBound', '2019-05-20 0:45');

--CHECK OUT THE TABLE 
SELECT *
FROM WAREHOUSE
ORDER BY event_datetime DESC;

--CALCULATING THE REMAININGS FROM EACH TIME PERIOD
WITH 
DAYS AS
	(SELECT TOP 1 OnHandQuantity AS LATEST_QUANTITY
		   	  ,	dateadd(DAY, -90, event_datetime) AS DAY_90
		 	  , dateadd(DAY, -180, event_datetime) AS DAY_180
		 	  , dateadd(DAY, -270, event_datetime) AS DAY_270
		 	  , dateadd(DAY, -365, event_datetime) AS DAY_365
	FROM WAREHOUSE
	ORDER BY event_datetime DESC), 

-- PERIOD 1: DAY 1 TO 90
SUM_InBound_1 AS
	(SELECT SUM(OnHandQuantityDelta) AS SUM_InBound
	FROM WAREHOUSE, DAYS
	WHERE event_datetime >= DAY_90 AND event_type = 'InBound'),

REMAINING_1 AS
	(SELECT CASE
			WHEN LATEST_QUANTITY > SUM_InBound_1.SUM_InBound THEN SUM_InBound_1.SUM_InBound
			ELSE LATEST_QUANTITY
			END AS REMAINING
	FROM SUM_InBound_1, DAYS), 

-- PERIOD 2: DAY 91 TO 180
SUM_InBound_2 AS
	(SELECT SUM(OnHandQuantityDelta) AS SUM_InBound
	FROM WAREHOUSE, DAYS
	WHERE event_datetime < DAY_90 AND event_datetime >= DAY_180 AND event_type = 'InBound'),

REMAINING_2 AS
	(SELECT CASE
		WHEN LATEST_QUANTITY - REMAINING_1.REMAINING >=  SUM_InBound_2.SUM_InBound THEN SUM_InBound_2.SUM_InBound
		ELSE LATEST_QUANTITY - REMAINING_1.REMAINING
		END AS REMAINING 
	FROM SUM_InBound_2, REMAINING_1, DAYS),

-- PERIOD 3: DAY 181 TO 270
SUM_InBound_3 AS
	(SELECT SUM(OnHandQuantityDelta) AS SUM_InBound
	FROM WAREHOUSE, DAYS
	WHERE event_datetime < DAY_180 AND event_datetime >= DAY_270 AND event_type = 'InBound'),

REMAINING_3 AS
	(SELECT CASE
		WHEN LATEST_QUANTITY - (REMAINING_1.REMAINING + REMAINING_2.REMAINING) >=  SUM_InBound_3.SUM_InBound THEN SUM_InBound_3.SUM_InBound
		ELSE LATEST_QUANTITY - (REMAINING_1.REMAINING + REMAINING_2.REMAINING)
		END AS REMAINING 
	FROM SUM_InBound_3, REMAINING_1, REMAINING_2, DAYS),

-- PERIOD 4: DAY 271 TO 365
SUM_InBound_4 AS
	(SELECT SUM(OnHandQuantityDelta) AS SUM_InBound
	FROM WAREHOUSE, DAYS
	WHERE event_datetime < DAY_270 AND event_datetime >= DAY_365 AND event_type = 'InBound'),

REMAINING_4 AS
	(SELECT CASE
		WHEN LATEST_QUANTITY - (REMAINING_1.REMAINING + REMAINING_2.REMAINING + REMAINING_3.REMAINING) >=  SUM_InBound_4.SUM_InBound THEN SUM_InBound_4.SUM_InBound
		ELSE LATEST_QUANTITY - (REMAINING_1.REMAINING + REMAINING_2.REMAINING + REMAINING_3.REMAINING)
		END AS REMAINING 
	FROM SUM_InBound_4, REMAINING_1, REMAINING_2, REMAINING_3, DAYS)

--CROSS JOINING THE RESULTS
SELECT REMAINING_1.REMAINING AS "0-90 days old",
	   REMAINING_2.REMAINING AS "91-180 days old",
	   REMAINING_3.REMAINING AS "181-270 days old",
	   REMAINING_4.REMAINING AS "271-365 days old"
FROM REMAINING_1, REMAINING_2, REMAINING_3, REMAINING_4;


--DELETE WAREHOUSE;
--DROP TABLE WAREHOUSE;


